server:
  port: 8080


spring:
 cloud:
  gateway:
   routes:
     - id: product-service
       uri: lb://PRODUCT-SERVICE
       predicates: 
        - Path=/product-service/**

     -  id: dahsboard-service
        uri: lb://PRODUCT-DASHBOARD-SERVICE
        predicates:
         - Path=/product-dashboard/**